{
 "title": "Trino JMX Copy",
 "description": "Trino",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Обзор состояния кластера", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Workers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "trino_failuredetector_name_HeartbeatFailureDetector_ActiveCount",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "trino_memory_name_ClusterMemoryManager_TotalAvailableProcessors",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "trino_memory_type_ClusterMemoryPool_name_general_ReservedDistributedBytes",
     "legendFormat": "Used"
    },
    {
     "expr": "trino_memory_type_ClusterMemoryPool_name_general_FreeDistributedBytes",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Running Queries",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(trino_execution_name_QueryManager_RunningQueries[6h])",
     "legendFormat": "6 hours"
    },
    {
     "expr": "trino_execution_name_QueryManager_RunningQueries",
     "legendFormat": "1 minute"
    }
   ]
  },
  {
   "title": "Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "increase(trino_execution_name_QueryManager_RunningQueries[1m])",
     "legendFormat": "Running"
    },
    {
     "expr": "increase(trino_execution_name_QueryManager_FailedQueries[1m])",
     "legendFormat": "Failed"
    },
    {
     "expr": "increase(trino_execution_name_QueryManager_QueuedQueries[1m])",
     "legendFormat": "Queued"
    },
    {
     "expr": "increase(trino_execution_name_QueryManager_AbandonedQueries[1m])",
     "legendFormat": "Abandoned"
    },
    {
     "expr": "increase(trino_execution_name_QueryManager_CanceledQueries[1m])",
     "legendFormat": "Canceled"
    }
   ]
  },
  {
   "title": "Cluster Memory Reservation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "trino_memory_name_ClusterMemoryManager_ClusterTotalMemoryReservation",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Errors by Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "increase(trino_execution_name_QueryManager_FailedQueries[1m])",
     "legendFormat": "Total"
    },
    {
     "expr": "increase(trino_execution_name_QueryManager_ExternalFailures[1m])",
     "legendFormat": "External"
    },
    {
     "expr": "increase(trino_execution_name_QueryManager_InternalFailures[1m])",
     "legendFormat": "Internal"
    },
    {
     "expr": "increase(trino_execution_name_QueryManager_UserErrorFailures[1m])",
     "legendFormat": "User Error"
    },
    {
     "expr": "increase(trino_execution_name_QueryManager_InsufficientResourcesFailures[1m])",
     "legendFormat": "Not Enough Resources"
    },
    {
     "expr": "increase(trino_memory_name_ClusterMemoryManager_NumberOfLeakedQueries[1m])",
     "legendFormat": "Memory Leak"
    },
    {
     "expr": "increase(trino_memory_name_ClusterMemoryManager_QueriesKilledDueToOutOfMemory[1m])",
     "legendFormat": "OOM"
    }
   ]
  },
  { "title": "Обработка запросов", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Время выполнения запроса",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "trino_execution_name_QueryManager_ExecutionTime_OneMinute[1m]",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "CPU Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(trino_execution_name_QueryManager_ConsumedCpuTimeSecs[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exchange Requests Failed !",
   "type": "timeseries",
   "description": "This means that coordinator unable to make HTTP requests to coordinator",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "increase(io_airlift_http_client_type_HttpClient_name_ForExchange_RequestFailed[1m])",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Minor GC Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(io_airlift_stats_name_GcMonitor_MinorGc_AllTime_sum[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Максимальная скорость обработки данных запроса",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "trino_execution_name_QueryManager_WallInputBytesRate_OneMinute_Max",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Средняя скорость обработки данных запроса",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "trino_execution_name_QueryManager_WallInputBytesRate_OneMinute_Avg",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Splits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "increase(trino_execution_scheduler_name_SplitSchedulerStats_WaitingForSource[1m])",
     "legendFormat": "Waiting Source"
    },
    {
     "expr": "increase(trino_execution_scheduler_name_SplitSchedulerStats_SplitQueuesFull[1m])",
     "legendFormat": "Queues Full"
    }
   ]
  },
  {
   "title": "SSL Certificate Expiration in",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "io_airlift_http_server_name_HttpServer_DaysUntilCertificateExpiration",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Рестарт координатора",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "io_airlift_node_name_NodeInfo_StartTime",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}